### ISSUE TITLE
SVG images not recogniced

### ISSUE THREAD

**Issue by Estartu** [cdgriffith/puremagic#37]
SVG images return mime_type='video/x-ms-asf'

**Comment by cdgriffith** [comment]
Thanks for the heads up! SVG was missing entirely, and probably because most regular magic number indexes don't include it as it's variable (it's just an XML file.) 

I have include the lookup for three common places I have seen it. If you happen to come across one that doesn't match, please open the file in a text editor and just reply to this thrad with the part up to `<svg `. 

For example one I found was: 

```
<?xml version="1.0" standalone="yes"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1">
<path style="fill:#ffffff; stroke:none;" d="M0 0L1 1L0 0z"/>
</svg>
```

And of course now thinking about it probably just easier to add a footer lookup for `</svg>`, but maybe will add that in next release if this one starts becoming a headache :) 

Added in 1.12
